import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/car/model.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh1_M_0135_DarkGray_0.geometry}
          material={materials.M_0135_DarkGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh1_Rims_0.geometry}
          material={materials.Rims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh1_Color_M02_0.geometry}
          material={materials.Color_M02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Mesh1_Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A_0
              .geometry
          }
          material={
            materials.Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh2__30_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh3__22_0.geometry}
          material={materials.material_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh4__16_0.geometry}
          material={materials.material_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh5_M_0135_DarkGray_0.geometry}
          material={materials.M_0135_DarkGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh5_Rims_0.geometry}
          material={materials.Rims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh5_Color_M02_0.geometry}
          material={materials.Color_M02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Mesh5_Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A_0
              .geometry
          }
          material={
            materials.Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh6__30_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh7__22_0.geometry}
          material={materials.material_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh8__16_0.geometry}
          material={materials.material_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh9__auto_16_0.geometry}
          material={materials.auto_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh10__auto_4_0.geometry}
          material={materials.auto_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh11__auto_16_0.geometry}
          material={materials.auto_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh12__auto_16_0.geometry}
          material={materials.auto_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto__0.geometry}
          material={materials.auto}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_1_0.geometry}
          material={materials.auto_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_3_0.geometry}
          material={materials.auto_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_3_0_1.geometry}
          material={materials.auto_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_3_0_2.geometry}
          material={materials.auto_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13_Color_M00_0.geometry}
          material={materials.Color_M00}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_4_0.geometry}
          material={materials.auto_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_5_0.geometry}
          material={materials.auto_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_6_0.geometry}
          material={materials.auto_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_7_0.geometry}
          material={materials.auto_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_8_0.geometry}
          material={materials.auto_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_8_0_1.geometry}
          material={materials.auto_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_8_0_2.geometry}
          material={materials.auto_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_10_0.geometry}
          material={materials.auto_10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_11_0.geometry}
          material={materials.auto_11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_13_0.geometry}
          material={materials.auto_13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_14_0.geometry}
          material={materials.auto_14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_14_0_1.geometry}
          material={materials.auto_14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_15_0.geometry}
          material={materials.auto_15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_16_0.geometry}
          material={materials.auto_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13__auto_17_0.geometry}
          material={materials.auto_17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh13_FrontColor_0.geometry}
          material={materials.FrontColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh14_M_0135_DarkGray_0.geometry}
          material={materials.M_0135_DarkGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh14_Rims_0.geometry}
          material={materials.Rims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh14_Color_M02_0.geometry}
          material={materials.Color_M02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Mesh14_Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A_0
              .geometry
          }
          material={
            materials.Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh15__30_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh16__22_0.geometry}
          material={materials.material_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh17__16_0.geometry}
          material={materials.material_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh18_M_0135_DarkGray_0.geometry}
          material={materials.M_0135_DarkGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh18_Rims_0.geometry}
          material={materials.Rims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh18_Color_M02_0.geometry}
          material={materials.Color_M02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Mesh18_Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A_0
              .geometry
          }
          material={
            materials.Porsche_718BoxsterSpyder_2020_Modified_CSB_Wheel1A
          }
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh19__30_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh20__22_0.geometry}
          material={materials.material_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh21__16_0.geometry}
          material={materials.material_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh22_FrontColor_0.geometry}
          material={materials.FrontColor}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model.glb");
